#!/usr/bin/env bash

if (($# != 0))
then
    # cluster="clusterA"
    cluster=$1
    # clusterB"
    echo "cluster: $cluster"
    kubectl get po --no-headers --all-namespaces --context=$cluster | awk -F' ' '{print $4}' | sort | uniq -c
else
    echo "Did not provide cluster"
fi
