#!/bin/bash

prompt="Please select a file:"
#options=( $(find -maxdepth 1 -print0 | xargs -0) )
options=( $(ls| xargs -0) )

PS3="$prompt "
select opt in "${options[@]}" "Quit" ; do
    if (( REPLY == 1 + ${#options[@]} ))
    then
        break
    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
        echo  "You picked $opt which is file $REPLY"
        source $opt
        break
    else
        echo "Invalid option. Try another one."
    fi
done
